name: Git Kexa Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

  
jobs:
  verify-malicious-npm-pkg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Kexa Action
        uses: 4urcloud/Kexa_githubAction@1.8.4
        id: kexa
        with:
          ENV_VARS: |
            GH1_GITHUBTOKEN=${{ secrets.GITHUB_TOKEN }}
            MYOWNRULES="./rules"
            NODE_CONFIG_TS_ENV=git

      - name: Check Kexa Action Result
        if: steps.kexa.outcome != 'success'
        run: |
          echo "Kexa Action failed with exit code $?. Exiting..."
          exit 1
